# Instructions
# 1. Load and explore the data.
##  - Remove redundant columns (Ranking, Year, Genre, Publisher) by creating 
##      a subset of the data frame.
##  - Create a summary of the new data frame.
# 2. Create plots to review and determine insights into data set.
##  - Create scatterplots, histograms and boxplots to gain insights into
##      the Sales data.
##  - Note your observations and diagrams that could be used to provide
##      insights to the business.
# 3. Include your insights and observations.

###############################################################################

# 1. Load and explore the data

# Install and import Tidyverse.


# Import the data set.


# Print the data frame.


# Create a new data frame from a subset of the sales data frame.
# Remove unnecessary columns. 


# View the data frame.


# View the descriptive statistics.


################################################################################

# 2. Review plots to determine insights into the data set.

## 2a) Scatterplots
# Create scatterplots.


## 2b) Histograms
# Create histograms.


## 2c) Boxplots
# Create boxplots.


###############################################################################

# 3. Observations and insights

## Your observations and insights here ......




# Import package.
library(tidyverse)

# Load the CSV file.
# You can use the specific file name if you are in the working directory.
df <- read.csv('turtle_sales.csv', header=TRUE)

# If you have to browse for the file, use file.choose().
df <- read.csv(file.choose(), header=TRUE)
# A window will open where you can browse and select the file.

# Check the current working directory
getwd()

# View the first few rows of the data frame
head(df)

# Display the structure of the data frame
str(df)

# Provide summary statistics of the data frame
summary(df)

sales_df <- subset(df, select = -c(Ranking, Year, Genre, Publisher))
head(sales_df)
# Display the structure of the data frame
str(sales_df)
# Provide summary statistics of the data frame
summary(sales_df)

# 2. Review plots to determine insights into the data set.

## 2a) Scatterplots
# Create scatterplots.
ggplot(sales_df, aes(x = Platform, y = Global_Sales)) +
  geom_point() +
  labs(x = "Platform", y = "Global Sales") +
  ggtitle("Scatterplot of the Global sales generated by each platform ")

ggplot(df, aes(x = Genre, y = Global_Sales)) +
  geom_point() +
  labs(x = "Genre", y = "Global Sales") +
  ggtitle("Scatterplot of the Global sales generated by each Genre ")

qplot(y=EU_Sales, data=df)

## 2b) Histograms
# Create histograms.
ggplot(sales_df, aes(x = Global_Sales)) +
  geom_histogram(binwidth = 1) +
  labs(x = "Global Sales", y = "Frequency") +
  ggtitle("Histogram of Global Sales")

ggplot(sales_df, aes(x = EU_Sales)) +
  geom_histogram(binwidth = 1) +
  labs(x = "EU Sales", y = "Frequency") +
  ggtitle("Histogram of EU Sales")


## 2c) Boxplots
# Create boxplots
ggplot(df, aes(x = Genre, y = Global_Sales)) +
  geom_boxplot() +
  labs(x = "Genre", y = "Global Sales") +
  ggtitle("Boxplot of Global Sales per Genre")

ggplot(df, aes(x = Genre, y = Global_Sales)) +
  geom_boxplot() +
  labs(x = "Genre", y = "Global Sales") +
  ggtitle("Boxplot of Global Sales per Genre")

qplot(Genre, Global_Sales, data=df, geom='boxplot')

# Week 5 assignment: Cleaning and maniulating data using R

## Utilising R, you will explore, prepare and explain the normality of the data
## set based on plots, Skewness, Kurtosis, and a Shapiro-Wilk test. Note that
## you will use this data set in future modules as well and it is, therefore, 
## strongly encouraged to first clean the data as per provided guidelines and 
## then save a copy of the clean data for future use.

## Instructions
# 1. Load and explore the data.
##  - Continue to use the data frame that you prepared in the Week 4 assignment. 
##  - View the data frame to sense-check the data set.
##  - Determine the `min`, `max` and `mean` values of all the sales data.
##  - Create a summary of the data frame.
# 2. Determine the impact on sales per product_id.
##  - Use the group_by and aggregate functions to sum the values grouped by
##      product.
##  - Create a summary of the new data frame.
# 3. Create plots to review and determine insights into the data set.
##  - Create scatterplots, histograms, and boxplots to gain insights into 
##     the Sales data.
##  - Note your observations and diagrams that could be used to provide 
##     insights to the business.
# 4. Determine the normality of the data set.
##  - Create and explore Q-Q plots for all sales data.
##  - Perform a Shapiro-Wilk test on all the sales data.
##  - Determine the Skewness and Kurtosis of all the sales data.
##  - Determine if there is any correlation between the sales data columns.
# 5. Create plots to gain insights into the sales data.
##  - Compare all the sales data (columns) for any correlation(s).
##  - Add a trend line to the plots for ease of interpretation.
# 6. Include your insights and observations.

################################################################################

# 1. Load and explore the data

# View data frame created in Week 4.
sales_df

# Check output: Determine the min, max, and mean values.
mean(sales_df$Global_Sales)
min(sales_df$Global_Sales)
max(sales_df$Global_Sales)

mean(sales_df$EU_Sales)
min(sales_df$EU_Sales)
max(sales_df$EU_Sales)

mean(sales_df$NA_Sales)
min(sales_df$NA_Sales)
max(sales_df$NA_Sales)

# View the descriptive statistics.
summary(sales_df)

###############################################################################

# 2. Determine the impact on sales per product_id.

## 2a) Use the group_by and aggregate functions.

# import library
library(dplyr)
# Group data based on Product and determine the sum per Product for Global Sales.


sales_summary <- sales_df %>%
  group_by(Product) %>%
  summarize(total_sales = sum(Global_Sales))

# View the data frame.
print(sales_summary)


# Explore the data frame.
# Call the function to calculate the mean.
mean(sales_summary$total_sales) 

# Call the function to calculate the median.
median(sales_summary$total_sales)


# Determine the minimum and maximum value.
min(sales_summary$total_sales)  
max(sales_summary$total_sales) 


# Range = Max - Min.
max(sales_summary$total_sales)- min(sales_summary$total_sales) 


# Calculate Q1 and Q3.
quantile(sales_summary$total_sales, 0.25)  
quantile(sales_summary$total_sales, 0.75)


# Use the summary() function.
summary(sales_summary$total_sales)


# Calculate IQR.
IQR(sales_summary$total_sales)  
# OR:
50.09 - 28.76


# Determine the variance.
var(sales_summary$total_sales)  


# Return the standard deviation.
sd(speedy$total_minutes)  



## 2b) Determine which plot is the best to compare game sales.
# Create scatterplots.
ggplot(sales_summary, aes(x = Product, y = total_sales)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Product", y = "Total Sales") +
  ggtitle("Scatterplot of Total Sales per product")

# Create histograms.
hist(sales_summary$total_sales) +
  labs(x = "Product", y = "Total Sales") +
  ggtitle("Histogram of Total Sales per product")
# Create boxplots.
boxplot(sales_summary$total_sales)

###############################################################################


# 3. Determine the normality of the data set.

## 3a) Create Q-Q Plots
# Create Q-Q Plots.
qqnorm(sales_summary$total_sales)

qqline(sales_summary$total_sales, col='red')


## 3b) Perform Shapiro-Wilk test
# Install and import Moments.
shapiro.test(sales_summary$total_sales)
install.packages('moments') 
library(moments)
# Perform Shapiro-Wilk test.

skewness(sales_summary$total_sales) 
kurtosis(sales_summary$total_sales)

## 3c) Determine Skewness and Kurtosis
# Skewness and Kurtosis.
skewness(sales_summary$total_sales)
# Our output suggests a positive skewness.


#Check for kurtosis.
kurtosis(sales_summary$total_sales)


## 3d) Determine correlation
# Determine correlation.
shapiro.test(sales_summary$Product)

#Since the p-value is much smaller than the significance level,we reject the null hypothesis. 
#In summary, the Shapiro-Wilk test indicates that the total_sales data does not follow a normal distribution. 
cor(sales_summary$Product, sales_summary$total_sales)

###############################################################################

# 4. Plot the data
# Create plots to gain insights into data.
# Choose the type of plot you think best suits the data set and what you want 
# to investigate. Explain your answer in your report.

#group data by product based on EU sales 
EUsales_summary <- sales_df %>%
  group_by(Product) %>%
  summarize(total_sales = sum(EU_Sales))

# View the data frame.
print(EUsales_summary)


# Explore the data frame.
# Call the function to calculate the mean.
mean(EUsales_summary$total_sales) 

# Call the function to calculate the median.
median(EUsales_summary$total_sales)


# Determine the minimum and maximum value.
min(EUsales_summary$total_sales)  
max(EUsales_summary$total_sales) 


# Range = Max - Min.
max(EUsales_summary$total_sales)- min(EUsales_summary$total_sales) 


# Calculate Q1 and Q3.
quantile(EUsales_summary$total_sales, 0.25)  
quantile(EUsales_summary$total_sales, 0.75)


# Use the summary() function.
summary(EUsales_summary$total_sales)


# Calculate IQR.
IQR(EUsales_summary$total_sales)  
# OR:
50.09 - 28.76
# Determine the variance.
var(EUsales_summary$total_sales)  


# Return the standard deviation.
sd(EUsales_summary$total_sales)  



## 2b) Determine which plot is the best to compare game sales.
# Create scatterplots.
ggplot(EUsales_summary, aes(x = Product, y = total_sales)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Product", y = "Total EU Sales") +
  ggtitle("Scatterplot of Total EU Sales per product")

# Create histograms.
hist(EUsales_summary$total_sales) +
  labs(x = "Product", y = "Total EU Sales") +
  ggtitle("Histogram of Total EU Sales per product")
# Create boxplots.
boxplot(EUsales_summary$total_sales)

###############################################################################


# 3. Determine the normality of the data set.

## 3a) Create Q-Q Plots
# Create Q-Q Plots.
qqnorm(EUsales_summary$total_sales)

qqline(EUsales_summary$total_sales, col='red')


## 3b) Perform Shapiro-Wilk test
# Install and import Moments.
shapiro.test(EUsales_summary$total_sales)
install.packages('moments') 
library(moments)
# Perform Shapiro-Wilk test.

skewness(EUsales_summary$total_sales) 
kurtosis(EUsales_summary$total_sales)

## 3c) Determine Skewness and Kurtosis
# Skewness and Kurtosis.
skewness(EUsales_summary$total_sales)
# Our output suggests a positive skewness.


#Check for kurtosis.
kurtosis(EUsales_summary$total_sales)


## 3d) Determine correlation
# Determine correlation.
shapiro.test(EUsales_summary$total_sales)

#Since the p-value is less than the significance level we reject the null hypothesis. 
#Therefore, the total_sales data is not normally distributed.
#In summary, the Shapiro-Wilk test indicates that the total_sales data does not follow a normal distribution.
cor(EUsales_summary$total_sales,sales_summary$total_sales)

# Our correlation coefficient of 1 suggests a positive correlation.

###############################################################################

# 4. Plot the data
# Create plots to gain insights into data.
# Choose the type of plot you think best suits the data set and what you want 
# to investigate. Explain your answer in your report.

min_sales <- min(sales_df$NA_Sales, sales_df$EU_Sales, sales_df$Global_Sales)
max_sales <- max(sales_df$NA_Sales, sales_df$EU_Sales, sales_df$Global_Sales)
mean_sales <- mean(c(sales_df$NA_Sales, sales_df$EU_Sales, sales_df$Global_Sales))

summary_df <- summary(sales_df)

summary_df

Tsales_summary <- sales_df %>%
  group_by(product_id) %>%
  summarize(total_sales = sum(sales_1 + sales_2 + sales_3))

ggplot(sales_df, aes(x = EU_Sales, y = NA_Sales)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "EU", y = "NA") +
  ggtitle("Scatterplot of European vs. N.American sales")

par(mfrow = c(1, 3))
qqnorm(sales_df$EU_Sales,main = "Q-Q Plot - EU Sales")
qqline(sales_df$EU_Sales,col='red')
qqnorm(sales_df$NA_Sales, main = "Q-Q Plot - NA Sales")
qqline(sales_df$Global_Sales,,col='red')
qqnorm(sales_df$Global_Sales, main = "Q-Q Plot - Global Sales")
qqline(sales_df$Global_Sales,,col='red')

shapiro_test_EUsales <- shapiro.test(sales_df$EU_Sales)
shapiro_test_NAsales <- shapiro.test(sales_df$NA_Sales)
shapiro_test_Globalsales <- shapiro.test(sales_df$Global_Sales)
###############################################################################

# 5. Observations and insights
# Your observations and insights here...



###############################################################################
###############################################################################
# Week 6 assignment: Making recommendations to the business using R

## The sales department wants to better understand if there is any relationship
## between North America, Europe, and global sales. Therefore, you need to
## investigate any possible relationship(s) in the sales data by creating a 
## simple and multiple linear regression model. Based on the models and your
## previous analysis (Weeks 1-5), you will then provide recommendations to 
## Turtle Games based on:
##   - Do you have confidence in the models based on goodness of fit and
##        accuracy of predictions?
##   - What would your suggestions and recommendations be to the business?
##   - If needed, how would you improve the model(s)?
##   - Explain your answers.

# Instructions
# 1. Load and explore the data.
##  - Continue to use the data frame that you prepared in the Week 5 assignment. 
# 2. Create a simple linear regression model.
##  - Determine the correlation between the sales columns.
##  - View the output.
##  - Create plots to view the linear regression.
# 3. Create a multiple linear regression model
##  - Select only the numeric columns.
##  - Determine the correlation between the sales columns.
##  - View the output.
# 4. Predict global sales based on provided values. Compare your prediction to
#      the observed value(s).
##  - NA_Sales_sum of 34.02 and EU_Sales_sum of 23.80.
##  - NA_Sales_sum of 3.93 and EU_Sales_sum of 1.56.
##  - NA_Sales_sum of 2.73 and EU_Sales_sum of 0.65.
##  - NA_Sales_sum of 2.26 and EU_Sales_sum of 0.97.
##  - NA_Sales_sum of 22.08 and EU_Sales_sum of 0.52.
# 5. Include your insights and observations.

###############################################################################

# 1. Load and explore the data


# Determine a summary of the data frame.


###############################################################################

# 2. Create a simple linear regression model
## 2a) Determine the correlation between columns
# Create a linear regression model on the original data.



## 2b) Create a plot (simple linear regression)
# Basic visualisation.


###############################################################################

# 3. Create a multiple linear regression model
# Select only numeric columns from the original data frame.


# Multiple linear regression model.


###############################################################################

# 4. Predictions based on given values
# Compare with observed values for a number of records.



###############################################################################

# 5. Observations and insights
# Your observations and insights here...



###############################################################################
###############################################################################